# Generated by Django 3.2.1 on 2023-03-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favourites',
            field=models.ManyToManyField(to='property.Property'),
        ),
    ]
